se/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('werewolves/', include("werewolves.urls"))
]

werewolves/urls.py
from django.urls import path, re_path

from . import views

app_name = "werewolves"

urlpatterns = [
    path("", views.redirect_to_lobby, name="default"),

    path("in_game_lobby/", views.base, name="in_game"),

    path('in_game_lobby/<str:lobby_name>/<str:lobby_status>/', views.lobby, name="lobby"),

    path("<str:lobby_name>/enter/", views.index, name="index"),

    path("all", views.day, name="day"),

    #path("day", views.day, name="day"),

    path("setup", views.setup, name="setup"),

    path("setup_night", views.setup_night, name="setup_night"),

    path("setup_night_werewolves", views.setup_night_werewolves, name="setup_night_werewolves"),

    path("setup_night_white_werewolf", views.setup_night_white_werewolf, name="setup_night_white_werewolf"),

    path("setup_night_seer", views.setup_night_seer, name="setup_night_seer"),

    path("setup_night_witch", views.setup_night_witch, name="setup_night_witch"),

    path("hunter", views.hunter, name="hunter"),

    #path("setup_night_hunter", views.setup_night_hunter, name="setup_night_hunter"),

    #path("setup_night_amor", views.setup_night_amor, name="setup_night_amor"),
    path("amor", views.setup_night_amor, name="setup_night_amor"),

    path("night", views.night, name="night"),

    path("villagers_win", views.villagers_win, name="villagers_win"),

    path("werewolves_win", views.werewolves_win, name="werewolves_win"),

    path("lovers_win", views.lovers_win, name = "lovers_win"),

    path("whitewerewolf_win", views.whitewerewolf_win, name = "whitewerewolf_win"),

    #path("end_game", views.end_game, name="end_game"),

    path("seer", views.seer_skill, name="seer_skill"),

    #path("seer_skill", views.seer_skill, name="seer_skill"),

    path("werewolf", views.werewolves_skill, name="werewolves_skill"),#(?P<theplayers>\w{0,50})/$

    path("villager", views.sleep_walking, name="sleep_walking"),

    path("whitewerewolf", views.white_skill, name="white_skill"),

    #path("white_skill", views.white_skill, name="white_skill"),

    path("witch", views.witch_skill, name="witch_skill"),

    ##path("witch_skill", views.witch_skill, name="witch_skill"),

    path("sleep_1", views.sleep_1, name="sleep_1"),

    path("sleep_accident", views.sleep_accident, name="sleep_accident"),

]

werewolves/models.py
from django.db import models

# Create your models here.

werewolves/views.py
import base64
import json

from asgiref.sync import async_to_sync, sync_to_async
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib import messages
from django.core import mail

from werewolves.WWManagementSystem import *
from django.shortcuts import redirect

from django.http import HttpResponseRedirect
from django.urls import reverse

#
# Instance of WWManagementSystem class
w = WWManagementSystem()

recent_players = []

# Global variables needed during the game
people_alive = list(w.players)
seer_list = []
werewolves_victim = []
turn = 0
from channels.layers import get_channel_layer



# Create your views here.

# Display index page

async def send_lobby_update_to_pre_lobby(): # this will be used to send updates to the pre_lobby in case a lobby is added or deleted
    channel_layer = get_channel_layer()
    with open('lobbies.json') as f: # get the lobbies which are saved in the json file
        data = json.load(f)
    await channel_layer.group_send(
        'preLobby2',
        {
            'type': 'send_list_of_lobbies', # this is the name of the function which will handle the message sending(function is located in the consumers.py inside the preConsumer class)
            'msgType': "updateLobbyList",
            'messages': data
        }
    )

def redirect_to_lobby(request): # so the user doesn't need to write the whole path werewolves/in_game_lobby. This automatically redirects the user there even if the user only writes werewolves/
    return redirect("in_game_lobby/")

def base(request):
    with open('lobbies.json') as f:
        data = json.load(f)
    return render(request, "werewolves/base.html",{
        "existing_lobbies" : data,
    })


def lobby(request, lobby_name, lobby_status):
    global w

    # send an invitation to a potential member of hClub
    if request.method == "POST":
        # lobby_name = base64.b64decode(lobby_name).decode('utf-8')
        url = f'http://127.0.0.1:8000/werewolves/in_game_lobby/{lobby_name}/join/'
        friends_email = request.POST['email']
        invited_by = request.POST["invited_by"]
        print(invited_by)
        subject = 'Werewolves Invitation'
        html_message = render_to_string('werewolves/invitation.html', {'context': 'values', 'url': url, 'invited_by':invited_by})
        plain_message = strip_tags(html_message)
        from_email = 'hclub.fh.krems@gmail.com'
        to_email = friends_email
        mail.send_mail(subject, plain_message, from_email, [to_email], html_message=html_message)
        messages.success(request, f'Thank you for sending an invitation to a potential Werewolves Player.')
        return render(request, 'werewolves/game_lobby.html')

    return render(request, "werewolves/game_lobby.html",{
        "lobby_name": lobby_name,
        "lobby_status": lobby_status,
        "wm":w,
        "users": []
    })

def index(request,lobby_name):
    return render(request, "werewolves/index.html")

# Check if we reach an end-game point
#def end_game(request):
    # Check if the condition for the lovers is fulfill
 #   if lovers_win(people_alive):
  #      return render(request, "werewolves/lovers_win.html", )
#
    # Check if the condition for the white werewolf is fulfill
 #   elif whitewerewolf_win(people_alive):
  #      return render(request, "werewolves/whitewerewolf_win.html", )

    # Check if the condition for the villagers is fulfill
   # elif villagers_win(people_alive):
    #    return render(request, "werewolves/villagers_win.html", )

    # Check if the condition for the werewolves is fulfill
    #elif werewolves_win(people_alive):
     #   return render(request, "werewolves/werewolves_win.html", )

def villagers_win(request):
    return render(request, "werewolves/villagers_win.html")
def werewolves_win(request):
    return render(request, "werewolves/werewolves_win.html")
def lovers_win(request):
    return render(request, "werewolves/lovers_win.html")
def whitewerewolf_win(request):
    return render(request, "werewolves/whitewerewolf_win.html")
def hunter(request):
    return render(request, "werewolves/hunter.html")


# display setup page
def setup(request, testing_session=False):
    global recent_players, people_alive
    args = {"players": recent_players}
    args["min_players"] = [1, 2, 3, 4, 5, 6]
    recent_players = []
    # condition for testing
    if testing_session:
        args = {"players": request.session["players"]}
    # if there are no players stored from the last game
    if "players" not in request.session:
        # create the key,value
        request.session["players"] = []
    # if the "load recent players" button is clicked
    if request.method == "POST" and "load_players" in request.POST:
        # assign the players form the session to recent_players
        recent_players = request.session["players"]
        return HttpResponseRedirect(reverse("werewolves:setup"))
    # if the "start setup night" button is clicked
    if request.method == "POST" and "players" in request.POST:
        # check if the amount of players exceeds the maximum
        if len(request.POST.getlist("players")) > 20:
            return HttpResponseRedirect(reverse("werewolves:setup"))
        # checks if there are duplicate values
        if get_player(request, wwSystem=w):
            people_alive = list(w.players)
            # save the players in the session for next use
            request.session["players"] = request.POST.getlist("players")
            return HttpResponseRedirect(reverse("werewolves:setup_night"))
        else:
            HttpResponseRedirect(reverse("werewolves:setup"))
    return render(request, "werewolves/setup.html", args)

# display setup_night page
def setup_night(request, testing=False):
    # checks if the request is type POST
    if request.method == "POST" and "werewolf" in request.POST:
        # checks and gets role numbers
        if check_role_numbers(request, wwSystem=w):
            get_role_numbers(request, wwSystem=w)
            return HttpResponseRedirect(reverse("werewolves:setup_night_werewolves"))
        else:
            return HttpResponseRedirect(reverse("werewolves:setup_night"))
    args = {"players": w.players}
    max_werewolves = len(args["players"])

    global turn, werewolves_victim, seer_list, people_alive
    turn = 0
    werewolves_victim = []
    seer_list = []
    people_alive = list(w.players)

    if max_werewolves % 2 == 0:
        max_werewolves = (max_werewolves // 2) - 1
    else:
        max_werewolves = max_werewolves // 2
    args["max_werewolves"] = max_werewolves
    # stores the suggestion in args
    suggestions = w.make_suggestions(len(args["players"]))
    for key, value in suggestions.items():
        args[key] = value
    if testing:
        # list of players for testing
        args = {"players": [Player("Thomas"), Player("Alvaro"), Player("Steve"), Player("Poseidon")]}
    return render(request, "werewolves/setup_night/setup_night.html", args)


# display setup_night_seer page
def setup_night_seer(request, testing=(False,None)): # testing[0]->enable testing, testing[1]-> pass role numbers
    role = "seer"
    # assigns a seer if there is one
    if request.method == "POST":
        data = request.POST.getlist(role)
        for name in data:
            w.assign_role(name, role)
        return HttpResponseRedirect(reverse("werewolves:setup_night_witch"))
    if testing[0]:
        w.roleNumbers = testing[1]
    # if there is no seer, redirect to the next page
    if w.roleNumbers[role] < 1:
        return HttpResponseRedirect(reverse("werewolves:setup_night_witch"))
    # arguments passed to render the html
    args = {"players": get_players_without_any_role(w.players)}
    return render(request, "werewolves/setup_night/setup_night_seer.html", args)


# display setup_night_werewolves page
def setup_night_werewolves(request, testing=(False, None)):
    role = "werewolf"
    # assigns werewolves
    if request.method == "POST":
        data = request.POST.getlist(role)
        for name in data:
            w.assign_role(name, role)
        return HttpResponseRedirect(reverse("werewolves:setup_night_white_werewolf"))
    if testing[0]:
        w.roleNumbers = testing[1]
    # if there are no werewolves, redirect to the next page
    if w.roleNumbers[role] < 1:
        return HttpResponseRedirect(reverse("werewolves:setup_night_white_werewolf"))
    # arguments passed to render the html
    args = {"nr_werewolves": list(range(1, w.roleNumbers[role]+1)),
            "players": get_players_without_any_role(w.players)}
    return render(request, "werewolves/setup_night/setup_night_werewolves.html", args)


# display setup_night_white_werewolf page
def setup_night_white_werewolf(request,testing=(False,None)):
    role = "whitewerewolf"
    # assigns the white werewolf if there is one
    if request.method == "POST":
        data = request.POST.getlist(role)
        for name in data:
            w.assign_role(name, role)
        return HttpResponseRedirect(reverse("werewolves:setup_night_seer"))
    if testing[0]:
        w.roleNumbers = testing[1]
    # if there is no whitewerewolf, redirect to the next page
    if w.roleNumbers[role] < 1:
        return HttpResponseRedirect(reverse("werewolves:setup_night_seer"))
    # arguments passed to render the html
    args = {"players": get_players_without_any_role(w.players)}
    return render(request, "werewolves/setup_night/setup_night_white_werewolf.html", args)

# display setup_night_witch page
def setup_night_witch(request,testing=(False,None)):
    role = "witch"
    # assigns the witch if there is one
    if request.method == "POST":
        data = request.POST.getlist(role)
        for name in data:
            w.assign_role(name, role)
        return HttpResponseRedirect(reverse("werewolves:setup_night_hunter"))
    if testing[0]:
        w.roleNumbers = testing[1]

werewolves/templates/werewolves/day.html
{% extends "werewolves/layout.html" %}
{% load static %}


{% block head %}

    <title>Day</title>
    <link href="{% static 'werewolves/day.css' %}" rel="stylesheet">
    <script src="{% static 'JS/day.js' %}"></script>

{% endblock %}


{% block body %}

    <div class="grid-container">
        <div class="item-table" >
            <img alt="table" class="table" src="{% static 'images/wood.jpg' %}">
        </div>

        <div class ="item-timer">
            <div class="timer">
                <span id="minutes"></span>:<span id="seconds"></span>
            </div>
        </div>

        <!-- Here comes the for loop iterating on the list of players -->
        <!-- For the name of the player -->
        {% for player in players %}

            <!-- Witch's potions -->
{#            {% if player.role == "witch" %}#}
{#                {% if not player.dead %}#}
{#                    {% if player.health_potion %}#}
{#                        <div class="item-life">#}
{#                            <img class="icon" alt="Health Potion" src="{% static 'images/life_potion.jpg' %}">#}
{#                        </div>#}
{##}
{#                    {% endif %}#}
{#                    {% if player.death_potion %}#}
{##}
{#                        <div class="item-death">#}
{#                            <img class="icon" alt="Death Potion" src="{% static 'images/death_potion.jpg' %}">#}
{#                        </div>#}
{##}
{#                    {% endif %}#}
{#                {% endif %}#}
{#            {% endif %}#}

            {% if player.dead %}
                <div class="item-player{{ player.id }}">
                    <p style="color: red"><strike>{{ player.name }}</strike></p>
                </div>
            {% else %}
                <div class="item-player{{ player.id }}">
                    <p>{{ player.name }}</p>
                </div>
            {% endif %}

            <!-- For the Icon of the player -->
            {% if player.dead %}
            <div class="item-player{{ player.id }}-icon">
                <img class="icon" alt="{{ player.role }}" src="{% static player.imgPath %}">
            </div>

            {% endif %}
        {% endfor %}

        <div class="item-votes">
            <form action = "{% url 'werewolves:day' %}" method="post" >
                {% csrf_token %}

                <div class="form-control">
                    <h1 class = "t">Player to kill: </h1>
                    <select class="custom-select" name = "victim">
                        <option value="" selected disabled hidden>Choose here</option>
                        {% for player in players %}
                            {% if not player.dead %}
                        <option style="font-weight: bold" value = "{{ player.id }}">{{ player.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="item-boton">
                    <button class="boton" type="submit">Verify</button>
                </div>

            </form>
        </div>
        <div class="item-boton-night">
            <form method="get" action="{% url 'werewolves:night' %}">
                <button class="boton-night">End Day</button>
            </form>
        </div>
    </div>

{% endblock %}

werewolves/templates/werewolves/dayVote.html
<!DOCTYPE html>
<html>
    <head>
        <title>Day</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <style>
            #turnPrompt{
                color: black;
                display: flex;
                justify-content: center;
            }
            #selection li{
                color: black;
            }
            div{
                padding: 30px 10px 30px 10px;
            }
        </style>
    </head>
    <body>
        <div style="vertical-align: center" >
            <h1 class="turn" ID="turnPrompt" style="margin: auto">Voting stage</h1>
            <ul id="selection" class="w3-ul w3-center" style="color: white; margin: auto" ></ul>
        </div>

        <script>
            /*
                * Display all the players by creating a new list item for each player, a vote_count_span which will show how many times a player was voted to be killed, and a custom attribute "data-votes" that will hold the number of votes
                * We can get the players array from the page where the ajax call to this page was made(index.html), and since the call is from that page this page has access to all the data and variables of the index.html
                * And the "players_array" can either be accessed as below or it can also directly be just used, no need to assign to the new variable all_players.
                *
                * Vote_update
                *   * Whenever a user clicks any of the the elements with the class "players_to_vote"(class which all the players list items have, as can be seen from inside the for loop),
                *   * we get the players clicked id(that is achieved by the event.target.id as seen in the second block of the code, event is the clicking event, event.target holds the element that was clicked)
                *   * and we get the player's data-vote which has the current amount of votes so the votes before the new vote here.
                *   * Then a new message will be sent to the server(consumers.py) and the message will contain the player's id that was voted and the current amount of votes.
                *   * Now on the server side(consumers.py) the server will take the player's id and the votes, and then it will increment the amount of votes by 1.
                *   * The server then saves the player's id and the new amount of votes in the list 'votes' inside the consumers.py to later check
                *   * which players were voted and which one had the most votes. After that the server sends back to the index.html a message of type also "vote_update" along with the player's id and  its votes.
                *   * And in the end the player's vote_count_span will be updated to show it to all the users active.
                *
                *
                *   send_kill()
                *   * After 30 seconds (setTimeout(send_kill, 30000)) the send_kill function will be called
                *   * The send_kill function will send a simple message to the server telling it that the voting time has expired and now the most voted player needs to be killed.
                *   * When we send the message of type "kill" , inside the consumers.py the server now finds the most number of votes and the player associated with that amount of votes..
                *   * ...from the list 'votes'.
                *   * It then updates the file "lobbies.json" by changing the attribute "isDead" of the player from False to True.
                *   * Then it sends back a message of type "kill" to the index.html along with the player with the most number of votes and the actual amount of votes.
                *   * And in the end inside the index.html the player's list-item will be crossed indicating that that player is now dead.
             */
            time_left = 30
            all_players = {{ "players_array"|safe }}
            players_selection = document.getElementById("selection")
            this_user = sessionStorage.getItem("user_name")
            for (player in all_players){
                if (all_players[player]["role"] != data.role && all_players[player]["isDead"] == "false"){
                    times = 0
                    var new_player_li = document.createElement("li")
                    var vote_count_span = document.createElement("span")
                    vote_count_span.appendChild(document.createTextNode("0"))
                    vote_count_span.setAttribute("class","w3-badge w3-right w3-margin-right")
                    vote_count_span.setAttribute("id", all_players[player]["user_name"] + "span")
                    new_player_li.setAttribute("id", all_players[player]["user_name"])
                    new_player_li.setAttribute("data-votes", times)
                    new_player_li.setAttribute("class","players_to_vote")
                    new_player_li.appendChild(document.createTextNode( all_players[player]["user_name"]))
                    new_player_li.appendChild(vote_count_span)
                    new_player_li.style.cursor = "pointer"
                    players_selection.appendChild(new_player_li)
                    if (user_name == all_players[player]["user_name"] || user_isDead=="true"){new_player_li.style.pointerEvents = "none";new_player_li.style.color = "gray";document.removeEventListener("click",send_new_vote)} // disable the ability for the user to vote for himself, or if it is dead
                }
            }

            if (user_isDead == "false")
                $(document).on("click",".players_to_vote",send_new_vote)

            function send_new_vote(event){
                $(".players_to_vote").css({"pointer-events":"none","color":"gray"})
              gameSocket.send(JSON.stringify({
                    "msgType" : "vote_update",
                    "msg": event.target.id,
                    "votes": event.target.getAttribute("data-votes"),
                    "user_name": user_name,
                    "user_type": user_type,
                }))
            }

            setTimeout(send_kill, 15000)
            function send_kill(){
                gameSocket.send(JSON.stringify({
                    "msgType" : "immediate_kill",
                    "msg": "",
                    "votes": "",
                    "user_name": user_name,
                    "user_type": user_type,
                }))
            }
        </script>
    </body>
</html>

werewolves/templates/werewolves/night_seer.html
{% extends "werewolves/layout.html" %}
{% load static %}

{% block head %}

    <title>Night</title>
        <style>
        body {
            background-image: url({% static 'images/seer.jpg' %});
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: fixed;

        }
    </style>

{% endblock %}

{% block body %}

    <div class="item-votes">
        <form action = "{% url 'werewolves:seer_skill' %}" method="post" >
            {% csrf_token %}

            <div style="vertical-align: center" class="form-control">
                <h1 class="t" style="margin: auto">
                    Reveal identity
                </h1>

                <select class="custom-select" name = "reveal">
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for player in players %}
                            {% if player not in seer_list and player.role != "seer" %}
                                <option style="font-weight: bold" value = "{{ player.id }}">{{ player.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div style="text-align: left ">
                <ul>
                    {% for p in seer_list %}
                        {% filter upper %}
                            {% if p.role == "werewolf" or p.role == "whitewerewolf" %}
                            <li style="color: red">{{ p.name }} --> "WEREWOLF"</li>
                            {% else %}
                            <li>{{ p.name }} --> "VILLAGER"</li>
                            {% endif %}
                        {% endfilter %}
                    {% empty %}
                        <li>Nothing revealed yet</li>
                    {% endfor %}
                </ul>
            </div>
            <div style="background-attachment: fixed">
                <button class="boton-seer" type="submit">Verify</button>
            </div>
        </form>
    </div>




        <div class="item-boton-night">
            {% if villager %}
                {% if len_villagers > 1 %}
                <form method="get" action="{% url 'werewolves:sleep_walking' %}">
                    <button class="boton-night2">Sleep Walking</button>
                </form>
                    {% else %}
                    <form method="get" action="{% url 'werewolves:werewolves_skill' %}">
                 <button class="boton-night2">Werewolves</button>
                </form>
                    {% endif %}

            {% else %}
                <form method="get" action="{% url 'werewolves:werewolves_skill' %}">
                 <button class="boton-night2">Werewolves</button>
                </form>
            {% endif %}
        </div>

{% endblock %}

werewolves/templates/werewolves/night_witch.html
{% extends "werewolves/layout.html" %}
{% load static %}

{% block head %}

    <title>Night</title>
    <link href="{% static 'werewolves/witch.css' %}" rel="stylesheet">

{% endblock %}

{% block body %}

    <div class="grid-container-witch">
        <div class="item-lab" >
            <img alt="Laboratory" class="lab" src="{% static 'images/lab_witch.jpg' %}">
        </div>

        <div class="title-witch">
            <h1 class="t" style="margin: auto; margin-top: 2%">
                Witch sees all the victims
            </h1>
        </div>

        {% if len_victims < 2 %}
        <div class="victimas">
        {% elif len_victims == 2 %}
        <div class="victimas2">
        {% else %}
        <div class="victimas3">
        {% endif %}

        <ul>
            {% for v in victims %}
                {% filter upper %}
                    <li style="display: inline; margin: 3%">{{ v.name }}</li>
                {% endfilter %}
            {% empty %}
                <li style="display: inline">No one died this turn</li>
            {% endfor %}
        </ul>
        </div>

    {% if witch.health_potion %}
                <div class="lab-life">
                <form action="{% url 'werewolves:witch_skill' %}" method="post">
                {% csrf_token %}
                    <h2 class="t">
                        Do you want to use your health potion?
                    </h2>
                    <select class="custom-health" name="heal">
                        <option value="" selected disabled hidden>Choose here</option>
                        {% for victim in victims %}
                            <option style="font-weight: bold" value = "{{ victim.id }}">{{ victim.name }}</option>
                        {% endfor %}
                    </select>
                <div>
                    <button class="boton-witch-life" type="submit">Heal</button>
                </div>
                </form>
                </div>
    {% endif %}
    {% if witch.death_potion %}

                <div class="lab-death">
                <form action="{% url 'werewolves:witch_skill' %}" method="post">
                {% csrf_token %}
                    <h2 class="t">
                        Do you want to use your death potion?
                    </h2>
                    <select class="custom-death" name="die">
                        <option value="" selected disabled hidden>Choose here</option>
                        {% for player in players %}
                            {% if player not in victims %}
                            <option style="font-weight: bold" value = "{{ player.id }}">{{ player.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>

                    <div class="item-boton-death">
                        <button class="boton-witch-death" type="submit">Poison</button>
                    </div>
                </form>

                </div>
    {% endif %}

            <div class="item-votes">
        <form action = "{% url 'werewolves:day' %}" method="post" >
            {% csrf_token %}

                <div style="background-attachment: fixed">
                    <button class="boton-witch" type="submit">Day</button>
                </div>
                    </form>
    </div>
        </div>
        </div>
    </div>


{% endblock %}

werewolves/templates/werewolves/sleep_1.html
{% extends "werewolves/layout.html" %}
{% load static %}

{% block head %}

    <title>Night</title>
        <style>
        body {
            background-image: url({% static 'images/seer.jpg' %});
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: fixed;

        }
        li {
            color: white;
            font-size: 30px;
        }
    </style>

{% endblock %}

{% block body %}

    <div class="item-votes">
        <form action = "{% url 'werewolves:sleep_1' %}" method="post" >
            {% csrf_token %}

            <div style="vertical-align: center" class="form-control">
                <h1 class="t" style="margin: auto">
                    Reveal identity
                </h1>

                <select class="custom-select" name = "reveal">
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for player in players %}
                            <option style="font-weight: bold" value = "{{ player.id }}">{{ player.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div style="text-align: left ">
            {% if saw %}
                <ul>
                        {% filter upper %}
                            {% if saw.role == "werewolf" or saw.role == "whitewerewolf" %}
                            <li style="color: red">{{ saw.name }} --> "WEREWOLF"</li>
                            {% else %}
                            <li>{{ saw.name }} --> "VILLAGER"</li>
                            {% endif %}
                        {% endfilter %}
                </ul>
            {% endif %}
            </div>
            <div class="item-boton" style="background-attachment: fixed">
                <button class="boton-seer" type="submit">Verify</button>
            </div>
        </form>
    </div>

        <div class="item-boton-night">
                <form method="get" action="{% url 'werewolves:werewolves_skill' %}">
                    <button class="boton-night2">Werewolves</button>
                </form>
        </div>

{% endblock %}

werewolves/templates/werewolves/sleep_accident.html
{% extends "werewolves/layout.html" %}
{% load static %}

{% block body %}
    <div class="t" style="position: absolute; bottom: 48%; left: 31%">
        <h1 style="font-size: 60px">{{ victim.name }} has died in a terrible accident </h1>
    </div>

    <div class="item-boton-night">
                <form method="get" action="{% url 'werewolves:werewolves_skill' %}">
                    <button class="boton-night2">Werewolves</button>
                </form>
        </div>
{% endblock %}